// Propuestas de temática para la trivia. Cada una es un banco que se agrega a «Mis bancos» con
// un toque y después se edita. Se pueden combinar copiando preguntas de uno a otro.
const q = (pregunta, correcta, ...incorrectas) => ({ tipo: 'pregunta', pregunta, correcta, incorrectas });

export const TRIVIAS = [
  {
    id: 'trivia-argentina',
    titulo: 'Trivia · Bien argentina',
    materia: 'Propuesta de trivia: historia, geografía, fútbol, música y cosas nuestras',
    items: [
      q('¿En qué año se declaró la independencia argentina?', '1816', '1810', '1853', '1806'),
      q('¿En qué ciudad se declaró la independencia?', 'San Miguel de Tucumán', 'Buenos Aires', 'Córdoba', 'Rosario'),
      q('¿Cuál es la montaña más alta de América?', 'El Aconcagua', 'El Lanín', 'El Fitz Roy', 'El Tupungato'),
      q('¿Quién escribió el Martín Fierro?', 'José Hernández', 'Jorge Luis Borges', 'Domingo F. Sarmiento', 'Julio Cortázar'),
      q('¿Quién dibujó a Mafalda?', 'Quino', 'Fontanarrosa', 'Caloi', 'Liniers'),
      q('¿En qué provincia están las Cataratas del Iguazú?', 'Misiones', 'Corrientes', 'Entre Ríos', 'Salta'),
      q('¿Cuántas provincias tiene Argentina?', '23', '24', '22', '25'),
      q('¿Qué invento se le atribuye a Ladislao Biro?', 'La birome', 'El colectivo', 'El dulce de leche', 'La tinta china'),
      q('¿Qué glaciar famoso se visita desde El Calafate?', 'El Perito Moreno', 'El Martial', 'El Vinciguerra', 'El Castaño Overa'),
      q('¿A qué selección le hizo Maradona el gol de «la mano de Dios»?', 'Inglaterra', 'Alemania', 'Bélgica', 'Italia'),
      q('¿Cuántos Mundiales ganó la selección argentina de fútbol masculino?', '3', '2', '4', '1'),
      q('¿Qué banda grabó «De música ligera»?', 'Soda Stereo', 'Los Redondos', 'Virus', 'Los Abuelos de la Nada'),
      q('¿Cuál es la capital de Chubut?', 'Rawson', 'Comodoro Rivadavia', 'Trelew', 'Puerto Madryn'),
      q('¿Quién cantaba «Mi Buenos Aires querido»?', 'Carlos Gardel', 'Julio Sosa', 'Hugo del Carril', 'Edmundo Rivero'),
      q('¿En qué año volvió la democracia a la Argentina?', '1983', '1976', '1989', '1982'),
    ],
  },
  {
    id: 'trivia-pantalla',
    titulo: 'Trivia · Cine, tele y música',
    materia: 'Propuesta de trivia: películas, series, dibujos y canciones que conoce todo el mundo',
    items: [
      q('¿Cómo se llama el café donde se juntan los amigos de «Friends»?', 'Central Perk', 'Monk\'s', 'Luke\'s', 'The Peach Pit'),
      q('¿En qué película de Disney suena «Hakuna Matata»?', 'El Rey León', 'Aladdín', 'Tarzán', 'Mulán'),
      q('¿Quién dirigió «Jurassic Park»?', 'Steven Spielberg', 'James Cameron', 'George Lucas', 'Ridley Scott'),
      q('¿Qué hechizo hace levitar las cosas en Harry Potter?', 'Wingardium Leviosa', 'Expelliarmus', 'Lumos', 'Alohomora'),
      q('¿Qué banda canta «Bohemian Rhapsody»?', 'Queen', 'The Beatles', 'ABBA', 'Pink Floyd'),
      q('¿En qué ciudad viven Los Simpson?', 'Springfield', 'Shelbyville', 'Quahog', 'South Park'),
      q('¿Quién canta «Thriller»?', 'Michael Jackson', 'Prince', 'Madonna', 'Lionel Richie'),
      q('¿En qué saga se dice «Que la fuerza te acompañe»?', 'Star Wars', 'Star Trek', 'Volver al futuro', 'Matrix'),
      q('¿Qué auto usan para viajar en el tiempo en «Volver al futuro»?', 'Un DeLorean', 'Un Mustang', 'Un Camaro', 'Un Cadillac'),
      q('¿Qué actor hizo de Jack en «Titanic»?', 'Leonardo DiCaprio', 'Brad Pitt', 'Matt Damon', 'Johnny Depp'),
      q('¿Cuál es el nombre verdadero de Batman?', 'Bruce Wayne', 'Clark Kent', 'Peter Parker', 'Tony Stark'),
      q('¿De qué país es Shakira?', 'Colombia', 'Venezuela', 'México', 'Puerto Rico'),
      q('¿Quién dice «¡Hasta el infinito y más allá!»?', 'Buzz Lightyear', 'Woody', 'Rayo McQueen', 'Shrek'),
      q('¿Cómo se llama el profesor de «El Chavo del 8»?', 'Jirafales', 'Longaniza', 'Ramón', 'Barriga'),
      q('¿En qué año salió el primer iPhone?', '2007', '2005', '2009', '2010'),
    ],
  },
  {
    id: 'trivia-general',
    titulo: 'Trivia · Cultura general',
    materia: 'Propuesta de trivia: ciencia, geografía y datos curiosos, para todas las edades',
    items: [
      q('¿Cuántas patas tiene una araña?', '8', '6', '10', '12'),
      q('¿Cuál es el planeta más grande del sistema solar?', 'Júpiter', 'Saturno', 'Neptuno', 'La Tierra'),
      q('¿Cuál es el océano más grande?', 'El Pacífico', 'El Atlántico', 'El Índico', 'El Ártico'),
      q('¿Cuántos huesos tiene el cuerpo de una persona adulta?', '206', '186', '226', '306'),
      q('¿Cuál es el símbolo químico del oro?', 'Au', 'Ag', 'Or', 'Go'),
      q('¿Quién pintó la Mona Lisa?', 'Leonardo da Vinci', 'Miguel Ángel', 'Rafael', 'Van Gogh'),
      q('¿Cuál es el animal terrestre más rápido?', 'El guepardo', 'El león', 'El antílope', 'El caballo'),
      q('¿Cuántos minutos tiene un día?', '1440', '1240', '1600', '1080'),
      q('¿Con qué fruta se hace el guacamole?', 'Palta', 'Pepino', 'Kiwi', 'Lima'),
      q('¿Qué país tiene forma de bota?', 'Italia', 'Grecia', 'Portugal', 'Chile'),
      q('¿Cuál es el río más largo de Sudamérica?', 'El Amazonas', 'El Paraná', 'El Orinoco', 'El Uruguay'),
      q('¿En qué año llegó el ser humano a la Luna?', '1969', '1959', '1972', '1965'),
      q('¿Qué idioma se habla en Brasil?', 'Portugués', 'Español', 'Brasileño', 'Italiano'),
      q('¿Cuántos colores tiene el arcoíris?', '7', '5', '6', '8'),
      q('¿En qué país están las pirámides de Guiza?', 'Egipto', 'México', 'Perú', 'Marruecos'),
    ],
  },
];
